version: 2

sources:
  - name: row
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
        tests:
          - unique:
              column_name: "(pdt_id|| '_' || orders_id)"
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: number of product
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: order
            tests:
              - unique
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: advertising campaigns
      - name: bing
        identifier: raw_gz_bing
        description: advertising campaigns
      - name: criteo
        identifier: raw_gz_criteo
        description: advertising campaigns
      - name: facebook
        identifier: raw_gz_facebook
        description: advertising campaigns
      - name: campaigns
        identifier: int_campaigns
        columns:
          - name: campaign_key
            description: PK
            tests:
              - unique
              - not_null